---
openapi: 3.0.3
info:
  title: String Operations
  description: |-
    This service performs string operations.
  version: 1.0.0
tags:
  - name: String Operations
    description: Basic string operations.
paths:
  /upper/{a}:
    get:
      tags:
      - string-operations
      description: Converts a string to UPPERCASE
      operationId: upper
      parameters:
        - name: a
          in: path
          required: true
          schema:
            type: string
          example: hello
      responses:
        '200':
          description: Successful operation.
          content:
            text/plain:
              schema:
                type: string
              example: HELLO
