package io.muehlbachler.bswe;

import org.springframework.stereotype.Service;

/**
 * A service class for performing string operations.
 *
 * @author Generated by ChatGPT 4.o
 */
@Service
public class StringService {
    /**
     * Converts all of the characters in the given string to uppercase.
     *
     * <p>This method returns a new string where all lowercase characters in
     * the input string are converted to their uppercase equivalents. If the
     * input string is already in uppercase or contains no alphabetic characters,
     * the original string is returned unchanged.</p>
     *
     * @param string the input string to be converted to uppercase. Must not be null.
     * @return a new string with all characters in uppercase, or the original string
     *         if it contains no lowercase characters.
     * @throws NullPointerException if the input string is null.
     * @author Generated by ChatGPT 4.o
     */
    public String toUpperCase(final String string) {
        return string.toUpperCase();
    }
}
