name: Backend CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    name: Unit Tests & Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Validate the checked-in Gradle wrapper
      - uses: gradle/wrapper-validation-action@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'
          cache: gradle

      # Setup Gradle with build cache
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable (just in case)
        run: chmod +x ./gradlew

      # Run tests and produce JaCoCo HTML (and XML if you ever want Codecov)
      - name: Run Tests + Coverage
        run: ./gradlew clean test jacocoTestReport

      # Always collect results even if tests fail
      - name: Upload JUnit Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: build/test-results/test
          retention-days: 7

      - name: Upload JaCoCo HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html
          retention-days: 7

  build:
    name: Build Backend
    runs-on: ubuntu-latest
    needs: [ tests ]
    steps:
      - uses: actions/checkout@v4

      - uses: gradle/wrapper-validation-action@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Build without re-running tests (they already ran in the tests job)
      - name: Build with Gradle
        run: ./gradlew clean assemble -x test

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: build/libs/*.jar
          if-no-files-found: error
          retention-days: 7
