name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: Unit Tests and Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Run Tests
        run: ./gradlew test
      - name: Upload JaCoCo HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html/

  build:
    name: Build Backend
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: build/libs/*.jar